### ISSUE TITLE
Game is restarted when app loses focus

### ISSUE THREAD

**Issue by jmiskovic** [a1studmuffin/Cataclysm-DDA-Android#59]
Whenever app is paused and resumed, game is completely restarted. This is not fully under control of user, for example phone can receive a call at any time. Autosave feature helps here, but it's not perfect as game loading takes some time. Ideal solution would be if game would just resume from same state as before it lost focus.

Edit:
I see this was purposely disabled  with [this commit](https://github.com/a1studmuffin/Cataclysm-DDA-Android/commit/245451d9d22efb65911f174e7498adda8ecc59a8). What were the reasons, and what needs to be changed so game can resume without issues?

**Comment by Dyrewulfe** [comment]
That commit is not the cause of the restarting, that was done to fix an issue that occurred when focus was restored. The game uses quite a bit of memory though, and Android kills background processes when memory is low.

Edit: To better explain that commit: Setting the mSurface to GONE when pausing causes the visible surface(basically the screen buffer) to be destroyed when the game loses focus. On resuming, the surface is recreated. Some quirks with how SDL works on Android made this necessary to avoid, in essence, losing track of the screen buffer(resulting in a permanent black screen on resuming).

**Comment by jmiskovic** [comment]
Sorry, I jumped to the conclusion and assumed that restarting app was intented behavior. After reading your comment and testing some more, it seems this is a bug affecting CDDA on my phone. Please let me know if this is reproducible.

Description:
App crashes when it comes back to focus.

Platform:
Xiaomi Redmi 3S on Android 6.0.1
RAM 3GB total, 900+ MB free, CDDA takes about 20 MB in main menu

Steps To Reproduce:
1) Start application
2) Put app in background (go to home screen, different app, or lock phone)
3) Bring app back to focus
4) Black screen appears for half a second and then app dies, phone goes to home screen
5) When trying to switch back to app again, app is restarted and state has to be reloaded from autosave

Expected result:
App resumes from state where it was when focus was lost.

Logcat excerpt:
(full log [here](https://pastebin.com/raw/ki5ATYag))
```
03-05 14:06:20.273  9727  9747 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x4 in tid 9747 (SDLThread)
03-05 14:06:20.377   639   639 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-05 14:06:20.377   639   639 F DEBUG   : Build fingerprint: 'Xiaomi/land/land:6.0.1/MMB29M/V9.2.2.0.MALMIEK:user/release-keys'
03-05 14:06:20.378   639   639 F DEBUG   : Revision: '0'
03-05 14:06:20.378   639   639 F DEBUG   : ABI: 'arm'
03-05 14:06:20.378   639   639 F DEBUG   : pid: 9727, tid: 9747, name: SDLThread  >>> com.MichaelDavies.CataclysmDDA <<<
03-05 14:06:20.378   639   639 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4
03-05 14:06:20.404   639   639 F DEBUG   :     r0 00000000  r1 00000000  r2 00000000  r3 00000000
03-05 14:06:20.405   639   639 F DEBUG   :     r4 df40c7d4  r5 ab28a670  r6 f6fe0e40  r7 ab59cd48
03-05 14:06:20.405   639   639 F DEBUG   :     r8 f6fe0e40  r9 dff61194  sl df40ca04  fp ef8e655c
03-05 14:06:20.405   639   639 F DEBUG   :     ip dfedbc38  sp df40c7a8  lr efa6e557  pc efa90d4c  cpsr 600f0030
03-05 14:06:20.417   639   639 F DEBUG   : 
03-05 14:06:20.417   639   639 F DEBUG   : backtrace:
03-05 14:06:20.418   639   639 F DEBUG   :     #00 pc 00088d4c  /data/app/com.MichaelDavies.CataclysmDDA-2/lib/arm/libSDL2.so (SDL_MapRGBA_REAL+3)
03-05 14:06:20.418   639   639 F DEBUG   :     #01 pc 00066553  /data/app/com.MichaelDavies.CataclysmDDA-2/lib/arm/libSDL2.so
03-05 14:06:20.418   639   639 F DEBUG   :     #02 pc 008b7417  /data/app/com.MichaelDavies.CataclysmDDA-2/lib/arm/libmain.so (_Z15refresh_displayv+170)
03-05 14:06:20.418   639   639 F DEBUG   :     #03 pc 008b7e31  /data/app/com.MichaelDavies.CataclysmDDA-2/lib/arm/libmain.so (_Z13CheckMessagesv+1448)
03-05 14:06:20.418   639   639 F DEBUG   :     #04 pc 008ba6df  /data/app/com.MichaelDavies.CataclysmDDA-2/lib/arm/libmain.so (_ZN13input_manager15get_input_eventEv+110)
03-05 14:06:20.419   639   639 F DEBUG   :     #05 pc 00456af9  /data/app/com.MichaelDavies.CataclysmDDA-2/lib/arm/libmain.so (_ZN13input_context12handle_inputEv+76)
03-05 14:06:20.419   639   639 F DEBUG   :     #06 pc 0055680d  /data/app/com.MichaelDavies.CataclysmDDA-2/lib/arm/libmain.so (_ZN9main_menu14opening_screenEv+1712)
03-05 14:06:20.419   639   639 F DEBUG   :     #07 pc 0054ea6d  /data/app/com.MichaelDavies.CataclysmDDA-2/lib/arm/libmain.so (SDL_main+2784)
03-05 14:06:20.419   639   639 F DEBUG   :     #08 pc 001b95b3  /data/app/com.MichaelDavies.CataclysmDDA-2/lib/arm/libmain.so (Java_org_libsdl_app_SDLActivity_nativeInit+230)
03-05 14:06:20.419   639   639 F DEBUG   :     #09 pc 00013981  /data/app/com.MichaelDavies.CataclysmDDA-2/oat/arm/base.odex (offset 0x12000)
03-05 14:06:20.480  1800  1800 D FancyDrawable: doPause:   [miui.maml.FancyDrawable@d635fcd]
03-05 14:06:20.480  1800  1800 D MultipleRenderable: setPause: true miui.maml.FancyDrawable@d635fcd
03-05 14:06:20.480  1800  1800 D RendererCore: self pause: miui.maml.RendererCore@264e73d
03-05 14:06:20.480  1800  1800 D ScreenElementRoot: pause
03-05 14:06:20.481  1800  1800 I NotifierManager: onUnregister: miui.maml.NotifierManager$MultiBroadcastNotifier@4f02ada
03-05 14:06:20.573   822   822 I MSM-irqbalance: Decided to move IRQ200 from CPU0 [P:0] to CPU4 [P:1] (banned)
03-05 14:06:20.882  2133  2158 I WtProcessController: Receive am_crash event for pid: 1343 pkg = com.MichaelDavies.CataclysmDDA
03-05 14:06:20.882  1343  9773 W ActivityManager:   Force finishing activity com.MichaelDavies.CataclysmDDA/.CataclysmDDA
03-05 14:06:20.882  2133  2158 W KloServer: Aborted broadcast does not supprt for: android
03-05 14:06:20.882   639   639 F DEBUG   : 
03-05 14:06:20.882   639   639 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_06
03-05 14:06:20.882   639   639 E DEBUG   : AM write failed: Broken pipe
03-05 14:06:20.883  3407  3442 I octvm_klo: get event file: /data/tombstones/tombstone_06
03-05 14:06:20.883  3407  3442 I octvm_klo: klo lock
03-05 14:06:20.884  1343  1388 I BootReceiver: Copying /data/tombstones/tombstone_06 to DropBox (SYSTEM_TOMBSTONE)
03-05 14:06:20.895  1343  9773 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
03-05 14:06:20.896  1343  9773 W CustomizeUtil: no getRealSize hack method
03-05 14:06:20.896  1343  9773 E ActivityManager: Invalid thumbnail dimensions: 0x0
03-05 14:06:20.926   438   438 E lowmemorykiller: Error writing /proc/9727/oom_score_adj; errno=22
03-05 14:06:20.927  1343  1400 W ActivityManager: Failed setting process group of 9727 to 9
03-05 14:06:20.928  1343  1400 W System.err: java.lang.IllegalArgumentException: Given thread does not exist
03-05 14:06:20.928  1343  1400 W System.err: 	at android.os.Process.setThreadScheduler(Native Method)
03-05 14:06:20.928  1343  1400 W System.err: 	at com.android.server.am.ActivityManagerService.applyOomAdjLocked(ActivityManagerService.java:19569)
03-05 14:06:20.928  1343  1400 W System.err: 	at com.android.server.am.ActivityManagerService.updateOomAdjLocked(ActivityManagerService.java:20141)
03-05 14:06:20.928  1343  1400 W System.err: 	at com.android.server.am.BroadcastQueue.processCurBroadcastLocked(BroadcastQueue.java:278)
03-05 14:06:20.928  1343  1400 W System.err: 	at com.android.server.am.BroadcastQueue.processNextBroadcast(BroadcastQueue.java:1151)
03-05 14:06:20.928  1343  1400 W System.err: 	at com.android.server.am.BroadcastQueue.processNextBroadcast(BroadcastQueue.java:697)
03-05 14:06:20.928  1343  1400 W System.err: 	at com.android.server.am.BroadcastQueue$BroadcastHandler.handleMessage(BroadcastQueue.java:174)
03-05 14:06:20.928  1343  1400 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-05 14:06:20.928  1343  1400 W System.err: 	at android.os.Looper.loop(Looper.java:157)
03-05 14:06:20.928  1343  1400 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:61)
03-05 14:06:20.928  1343  1400 W System.err: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
03-05 14:06:20.930  1343  1400 D ActivityManager: Set Ui thread(TID 2542) and RenderThread(TID 2935) to sched FIFO
03-05 14:06:20.945  1343  1400 I ActiveServicesInjector: Low priority start of: ServiceRecord{c0590e4 u0 com.google.android.gms/.stats.service.DropBoxEntryAddedService}
03-05 14:06:20.949  3407  3442 I octvm_klo: summary:[signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4
03-05 14:06:20.949  3407  3442 I octvm_klo: ]
03-05 14:06:20.950  3407  3442 I octvm_klo: summary: [/data/app/com.MichaelDavies.CataclysmDDA-2/lib/arm/libSDL2.so (SDL_MapRGBA_REAL+3)]
03-05 14:06:20.950  3407  3442 I octvm_klo: start gathering logcat log...
03-05 14:06:20.960  3407  3442 I octvm_klo: gethering logcat log done
03-05 14:06:20.960  3407  3442 I octvm_klo: klo unlock
03-05 14:06:20.971  1343  2524 D GraphicsStats: Buffer count: 6
03-05 14:06:20.971  1343  1819 I WindowState: WIN DEATH: Window{2578084 u0 com.MichaelDavies.CataclysmDDA/com.MichaelDavies.CataclysmDDA.CataclysmDDA}
03-05 14:06:20.974  1343  2007 I ActivityManager: Process com.MichaelDavies.CataclysmDDA (pid 9727) has died
03-05 14:06:20.974   659   659 I Zygote  : Process 9727 exited due to signal (11)
03-05 14:06:20.975  1343  2007 D ActivityManager: cleanUpApplicationRecord -- 9727
```

**Comment by Dyrewulfe** [comment]
It's reproducible, but... I can't reproduce it. I've been digging through crash reports, and this is common on a number of devices. Of course, luck would have it that it doesn't affect any of my 3. I "think" I have this one figured out, though. Would you be willing to test some builds for me in an attempt to lick this?

**Comment by jmiskovic** [comment]
Yeah, I'd be happy to test your builds. I'm very interested to have it working on my phone.

**Comment by Dyrewulfe** [comment]
Alright, thank you. I will contact you in the next day or three.

Also, you might try changing from software to hardware rendering in the graphics options in the meantime. Most devices suffer a performance hit with HW, but HW is much more stable. (the commit you pointed to was a software "loss of screen surface" fix(for software rendering), and I'm certain this is as well.)

**Comment by jmiskovic** [comment]
I can confirm that HW rendering doesn't crash. I can't see any performance degradation, so it's a great workaround. Thanks for pointing it out.
